name: Kristalball

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Run app (optional)
      run: |
        # Run your main script if needed
        python app.py || echo "app.py not found, skipping"

    - name: Execute notebook (optional)
      run: |
        pip install nbconvert jupyter
        mkdir -p results
        jupyter nbconvert --to notebook --execute main.ipynb --output results/main_out.ipynb
    
    - name: Save trained model artifacts
      if: success() && always()
      uses: actions/upload-artifact@v4
      with:
        name: xgb-models
        path: |
          xgb_inventory_model.pkl
          xgb_model_features.pkl

    - name: Run tests (if available)
      run: |
        if [ -d tests ]; then
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q
        else
          echo "No tests folder found, skipping"
        fi
