name: Kristalball

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Run app (optional)
      run: |
        # Run your main app
        python app.py

    - name: Execute notebook (optional)
      uses: stefanzweifel/gha-run-notebook@v1
      with:
        notebook-path: main.ipynb
        output-path: results/main_out.ipynb

    - name: Save trained model artifacts
      if: success() && always()
      uses: actions/upload-artifact@v3
      with:
        name: xgb-models
        path: |
          xgb_inventory_model.pkl
          xgb_model_features.pkl

    - name: Run tests (if you have them)
      run: |
        # For example, run pytest if you create tests
        pytest --maxfail=1 --disable-warnings -q
